[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         opentelemetry
    Listen       0.0.0.0
    Port         4318
    Tag          otel.*

[OUTPUT]
    Name         output
    Match        *
